FORMAT: 1A
HOST: https://digipass-api.herokuapp.com/api

# digipass

Digipass provides a simple API to access all preferences of users that are authorized to your app.

## Users [/users]

### Create new account [POST]

+ Request (application/json)

        {
            "username": "digipass@example.com",
            "password": "password",
            "name": {
                "first": "Digi",
                "last": "Pass"
            }
        }


+ Response 200 (application/json; charset=utf-8)

        {
            "Bearer": "R_7XUe6TEYQJlYNeF-njnl50",
            "User": {
                "id": "5760262342616610008e62f3"
            }
        }